Created initial figure set
klepzers/chess pull request #6
Opened 2021-01-19 15:52 UTC by Toms-R

Created initial figure set - https://github.com/klepzers/chess/issues/2

2021-01-19 15:54 UTC, klepzers requested changes
visuals.js izmaiņas noņem nost no commita! :)

2021-01-19 15:54 UTC, klepzers commented
git add . vairs neies cauri

2021-01-19 16:48 UTC, klepzers requested changes

2021-01-19 16:48 UTC, klepzers commented on visual.js
> -    img.addEventListener("load", function () {
This change is not relevant to current PR

2021-01-19 16:48 UTC, klepzers commented on visual.js
> +    startingPositions.forEach(function(piece) {
This change is not relevant to current PR

2021-01-19 16:48 UTC, klepzers commented on visual.js
> +// Define starting positions from logic.js.
This change is not relevant to current PR

2021-01-19 16:48 UTC, klepzers commented on logic.js
> +}
No newline at the end of the file.

2021-01-19 20:22 UTC, klepzers approved these changes
Everything is fine now :)

2021-01-20 16:50 UTC, klepzers approved these changes
console.log should be removed after yellow dots functionality is done.

2021-01-20 17:13 UTC, austramarta approved these changes

2021-01-20 18:39 UTC, merged